# Learning Numpy

## Theory

### Import Numpy

In [1]:
import numpy as np

### Create basic array

In [2]:
np.zeros(2)

array([0., 0.])

In [3]:
np.ones(1)

array([1.])

In [4]:
np.empty(2)

array([0., 0.])

In [5]:
np.arange(10)
np.arange(2,10,3)

array([2, 5, 8])

In [6]:
py_list = [1,2,3,4,5]
np.array(py_list)

array([1, 2, 3, 4, 5])

### Basic Functions

In [66]:
monthly_closings_aapl_2020 = np.array([100,102,103,101,96,111,113,116,120,150,140,134])
monthly_closings_aapl_2021 = np.array([136,144,138,150,180,142,145,150,165,177,165,155])

In [67]:
monthly_closings_aapl_2021.shape

(12,)

In [9]:
np.sort(monthly_closings_aapl_2020)

array([ 96, 100, 101, 102, 103, 111, 113, 116, 120, 134, 140, 150])

In [10]:
np.concatenate(monthly_closings_aapl_2020, monthly_closings_aapl_2021)

TypeError: only integer scalar arrays can be converted to a scalar index

Working with two dimensions

With .reshape() we can change the shape of an array.
Note: New Array needs to have same number of elements as original array.


In [12]:
quarterly_closing_aapl_2020 = monthly_closings_aapl_2020.reshape(4,3) #quarterly 
quarterly_closing_aapl_2020

array([[100, 102, 103],
       [101,  96, 111],
       [113, 116, 120],
       [150, 140, 134]])

In [13]:
quarterly_closing_aapl_2020[1, 2]

np.int64(111)

### Slicing

In [14]:
# Get Closing Prices < 105
monthly_closings_aapl_2020[monthly_closings_aapl_2020 < 105]

array([100, 102, 103, 101,  96])

In [ ]:
# Get Closing Prices > 120 & < 130
monthly_closings_aapl_2020[(monthly_closings_aapl_2020 > 120) & (monthly_closings_aapl_2020 < 130)]

### Math Functions

In [15]:
monthly_closings_aapl_2020.sum()

np.int64(1386)

In [16]:
monthly_closings_aapl_2020.min()

np.int64(96)

In [17]:
monthly_closings_aapl_2020.max()

np.int64(150)

In [18]:
# broadcasting
monthly_closings_aapl_2020 * 1.1

array([110. , 112.2, 113.3, 111.1, 105.6, 122.1, 124.3, 127.6, 132. ,
       165. , 154. , 147.4])

In [37]:
np.random.uniform(-3,3, 10)

array([ 0.92573367, -1.54199532,  0.91465795, -0.26405601, -2.70820574,
        2.59157396,  0.67199894, -2.7433221 , -2.99453061,  1.97281355])

## Excercise 1
### NumPy Exercise: Portfolio Analysis and Risk Management

### Learning Objectives
- Master NumPy array creation, indexing, and slicing
- Apply NumPy operations to financial data
- Implement functions with input validation
- Combine NumPy with control flow structures

---

### Exercise 1: Stock Portfolio Analysis
#### Background
You are a portfolio analyst managing a portfolio of 5 stocks over 10 trading days. You need to analyze the daily prices and calculate various performance metrics.

#### Task 1.1: Create the Portfolio Data (2 points)

Create a 2D NumPy array called `portfolio_prices` with shape (10, 5) representing:
- **Rows**: 10 trading days
- **Columns**: 5 different stocks (Stock A, B, C, D, E)

Use the following initial prices for Day 0:
- Stock A: 100, Stock B: 50, Stock C: 75, Stock D: 120, Stock E: 30

Generate random daily returns between -3% and +3% for each subsequent day using `np.random.uniform()`.

**Hint**: Use cumulative products to simulate realistic price movements.
```python

---

#### Task 1.2: Basic Indexing and Slicing (3 points)

Using the `portfolio_prices` array, extract the following:

a) The prices of Stock C on all days  
b) The prices of all stocks on Day 5  
c) The prices of Stocks B, C, and D on Days 3 to 7 (inclusive)  
d) The last closing price of each stock
```python

---

#### Task 1.3: Calculate Daily Returns (4 points)

Write a function `calculate_returns(prices)` that:
- Takes a 2D array of prices (shape: days × stocks)
- **Validates** that the input is a 2D NumPy array with at least 2 rows
- Calculates daily percentage returns for each stock
- Returns a 2D array with shape (days-1, stocks)

**Formula**: Return = (Price_today - Price_yesterday) / Price_yesterday * 100
```python

---

#### Task 1.4: Portfolio Performance Metrics (5 points)

Calculate the following metrics using NumPy functions:

a) **Mean daily return** for each stock  
b) **Standard deviation (volatility)** for each stock  
c) **Best performing stock** (highest mean return)  
d) **Worst performing stock** (lowest mean return)  
e) **Total portfolio return** (assuming equal weights of 20% each)
```python

---

#### Bonus Challenge (Optional, +3 points)

Create a function `stress_test_portfolio(prices, shock_percentage)` that:
- Takes the portfolio_prices array and a shock percentage (e.g., -20 for -20% crash)
- Applies the shock to all prices simultaneously
- Recalculates all metrics from Exercise 1.4
- Returns a dictionary with the stressed metrics
- Uses try-except for error handling
```python